version: "3.8"

# TODO: setup
services:
    backend:
        build: ./backend
        ports:
            - 8000:8000
        environment:
            - DATABASE_URL=postgresql+asyncpg://....

    workflow-runner:
        build: ./workflow-runner
        ports:
            - 4000:8000
        environment:
            # TODO:

    web:
        build: ./web
        ports:
            - 3000:3000
        environment:
            # TODO:
