blank_issues_enabled: false
version: 1.0
contact_links:
  - name: Discord (Question, Problem, Support, Feature Requests, etc.)
    url: https://discord.gg/GqbJZT9Hbf
    about: General community discussions