"""rename control table

Revision ID: 48422348dba4
Revises: 63f98bfe65eb
Create Date: 2024-11-13 13:01:03.972532

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "48422348dba4"
down_revision: Union[str, None] = "63f98bfe65eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_controls_results",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workflow_id", sa.TEXT(), nullable=False),
        sa.Column("run_id", sa.TEXT(), nullable=False),
        sa.Column("result", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workflow_id"], ["workflows.workflow_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("workflow_id", "run_id"),
    )
    op.drop_table("workflow_controls")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_controls",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("workflow_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("run_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("result", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.workflow_id"],
            name="workflow_controls_workflow_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("workflow_id", "run_id", name="workflow_controls_pkey"),
    )
    op.drop_table("workflow_controls_results")
    # ### end Alembic commands ###
