"""remove workflow_id from workflow_runs table

Revision ID: 7b3d4391fadf
Revises: 5f18aaca662b
Create Date: 2024-09-11 17:33:48.650598

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa F401


# revision identifiers, used by Alembic.
revision: str = "7b3d4391fadf"
down_revision: Union[str, None] = "5f18aaca662b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflow_runs", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workflow_runs", sa.Column("user_id", sa.TEXT(), nullable=False))
    # ### end Alembic commands ###
