"""introduce composed primary key for secrets table

Revision ID: 7e5d82221765
Revises: db5cf73c0869
Create Date: 2024-11-05 10:52:24.394416

"""

from typing import Sequence, Union

from alembic import op
import sqlmodel  # noqa F401


# revision identifiers, used by Alembic.
revision: str = "7e5d82221765"
down_revision: Union[str, None] = "db5cf73c0869"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("""
        ALTER TABLE secrets
        DROP CONSTRAINT secrets_pkey,
        ADD PRIMARY KEY (secret_id, user_id)
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("""
        ALTER TABLE secrets
        DROP CONSTRAINT secrets_pkey,
        ADD PRIMARY KEY (secret_id)
    """)

    # ### end Alembic commands ###
