"""add error column to workflow_runs table

Revision ID: cb77796bf169
Revises: 7985f1c159a3
Create Date: 2024-11-27 14:02:45.249467

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa F401


# revision identifiers, used by Alembic.
revision: str = "cb77796bf169"
down_revision: Union[str, None] = "7985f1c159a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workflow_runs", sa.Column("error", sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflow_runs", "error")
    # ### end Alembic commands ###
