services:
    web:
        build:
            context: ../web
            dockerfile: ../docker/Dockerfile.web
        image: admyralai/web:latest

    api:
        build:
            context: ..
            dockerfile: ./docker/Dockerfile.api
        image: admyralai/api:latest

    worker:
        build:
            context: ..
            dockerfile: ./docker/Dockerfile.worker
        image: admyralai/worker:latest
