"""migrate icon column workflow_template_metadata to integrationtype

Revision ID: 37d9571b67ee
Revises: ac90cdc48150
Create Date: 2024-05-22 14:06:07.786046

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37d9571b67ee'
down_revision = 'ac90cdc48150'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE admyral.integrationtype ADD VALUE 'YARAIFY';")
        op.execute("ALTER TYPE admyral.integrationtype ADD VALUE 'THREATPOST';")
        op.execute("ALTER TYPE admyral.integrationtype ADD VALUE 'PHISH_REPORT';")

    op.execute((
        """
        ALTER TABLE admyral.workflow_template_metadata 
            ALTER COLUMN icon DROP NOT NULL
        """
    ))
    op.execute((
        """
        ALTER TABLE admyral.workflow_template_metadata 
            ALTER COLUMN icon TYPE admyral.integrationtype USING admyral.workflow_template_metadata.icon::text::admyral.integrationtype
        """
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_template_metadata', 'icon',
               existing_type=postgresql.ENUM('VIRUS_TOTAL', 'ALIENVAULT_OTX', 'YARAIFY', 'THREATPOST', 'PHISH_REPORT', name='integrationtype', schema='admyral'),
               type_=sa.TEXT(),
               nullable=False,
               schema='admyral')

    op.execute("ALTER TYPE admyral.integrationtype RENAME TO integrationtype_old")
    op.execute("CREATE TYPE admyral.integrationtype AS ENUM('VIRUS_TOTAL', 'ALIENVAULT_OTX')")
    op.execute((
        "ALTER TABLE admyral.credential ALTER COLUMN credential_type TYPE admyral.integrationtype USING admyral.credential.credential_type::text::admyral.integrationtype"
    ))
    op.execute("DROP TYPE admyral.integrationtype_old")
    # ### end Alembic commands ###
