"""add prev_action_state_id column to workflow_run_action_state

Revision ID: 43707d4b8f9c
Revises: fb54865daf72
Create Date: 2024-04-24 21:17:55.612419

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '43707d4b8f9c'
down_revision = 'fb54865daf72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_run_action_state', sa.Column('prev_action_state_id', sa.UUID(as_uuid=False), nullable=True), schema='admyral')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_run_action_state', 'prev_action_state_id', schema='admyral')
    # ### end Alembic commands ###
