"""remove integrationtype enum

Revision ID: 81da09e8f6fc
Revises: ac3bdb61a563
Create Date: 2024-05-28 16:04:51.456609

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '81da09e8f6fc'
down_revision = 'ac3bdb61a563'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credential', 'credential_type',
               existing_type=postgresql.ENUM('VIRUS_TOTAL', 'ALIENVAULT_OTX', 'YARAIFY', 'THREATPOST', 'PHISH_REPORT', 'SLACK', 'JIRA', name='integrationtype'),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='admyral')
    op.alter_column('workflow_template_metadata', 'icon',
               existing_type=postgresql.ENUM('VIRUS_TOTAL', 'ALIENVAULT_OTX', 'YARAIFY', 'THREATPOST', 'PHISH_REPORT', 'SLACK', 'JIRA', name='integrationtype'),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='admyral')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    enum_type = postgresql.ENUM('VIRUS_TOTAL', 'ALIENVAULT_OTX', 'YARAIFY', 'THREATPOST', 'PHISH_REPORT', 'SLACK', 'JIRA', name='integrationtype', schema='admyral')
    enum_type.create(op.get_bind(), checkfirst=True)

    op.execute((
        """
        ALTER TABLE admyral.workflow_template_metadata 
            ALTER COLUMN icon TYPE admyral.integrationtype USING admyral.workflow_template_metadata.icon::text::admyral.integrationtype
        """
    ))
    op.execute((
        """
        ALTER TABLE admyral.credential 
            ALTER COLUMN credential_type TYPE admyral.integrationtype USING admyral.credential.credential_type::text::admyral.integrationtype
        """
    ))
    # ### end Alembic commands ###
