"""add note workflow node type
Revision ID: 8bc2d1453ebe
Revises: 43707d4b8f9c
Create Date: 2024-04-27 22:46:17.422331
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8bc2d1453ebe'
down_revision = '43707d4b8f9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE admyral.actiontype ADD VALUE 'NOTE';")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE admyral.actiontype RENAME TO actiontype_old")
    op.execute("CREATE TYPE admyral.actiontype AS ENUM('HTTP_REQUEST', 'WEBHOOK', 'IF_CONDITION', 'AI_ACTION', 'SEND_EMAIL')")
    op.execute((
        "ALTER TABLE admyral.action_node ALTER COLUMN action_type TYPE admyral.actiontype USING admyral.action_node.action_type::text::admyral.actiontype"
    ))
    op.execute("DROP TYPE admyral.actiontype_old")
    # ### end Alembic commands ###