"""add integration action type

Revision ID: a89c45ac9f76
Revises: b16c43b35cd9
Create Date: 2024-05-21 10:34:48.152284

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a89c45ac9f76'
down_revision = 'b16c43b35cd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE admyral.actiontype ADD VALUE 'INTEGRATION';")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE admyral.actiontype RENAME TO actiontype_old")
    op.execute("CREATE TYPE admyral.actiontype AS ENUM('HTTP_REQUEST', 'WEBHOOK', 'IF_CONDITION', 'AI_ACTION', 'SEND_EMAIL', 'NOTE', 'MANUAL_START')")
    op.execute((
        "ALTER TABLE admyral.action_node ALTER COLUMN action_type TYPE admyral.actiontype USING admyral.action_node.action_type::text::admyral.actiontype"
    ))
    op.execute("DROP TYPE admyral.actiontype_old")
    # ### end Alembic commands ###
