"""add jira to integration type

Revision ID: ac3bdb61a563
Revises: d4cd7f559526
Create Date: 2024-05-27 16:47:21.571420

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac3bdb61a563'
down_revision = 'd4cd7f559526'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE admyral.integrationtype ADD VALUE 'JIRA';")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE admyral.integrationtype RENAME TO integrationtype_old")
    op.execute("CREATE TYPE admyral.integrationtype AS ENUM('VIRUS_TOTAL', 'ALIENVAULT_OTX', 'YARAIFY', 'THREATPOST', 'PHISH_REPORT', 'SLACK')")
    op.execute((
        "ALTER TABLE admyral.credential ALTER COLUMN credential_type TYPE admyral.integrationtype USING admyral.credential.credential_type::text::admyral.integrationtype"
    ))
    op.execute((
        "ALTER TABLE admyral.workflow_template_metadata ALTER COLUMN icon TYPE admyral.integrationtype USING admyral.workflow_template_metadata.icon::text::admyral.integrationtype"
    ))    
    op.execute("DROP TYPE admyral.integrationtype_old")
    # ### end Alembic commands ###
