"""add manual workflow start

Revision ID: b1ef28c0bf5d
Revises: b43779be43da
Create Date: 2024-05-02 12:07:40.838081

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1ef28c0bf5d'
down_revision = 'b43779be43da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE admyral.actiontype ADD VALUE 'MANUAL_START';")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE admyral.actiontype RENAME TO actiontype_old")
    op.execute("CREATE TYPE admyral.actiontype AS ENUM('HTTP_REQUEST', 'WEBHOOK', 'IF_CONDITION', 'AI_ACTION', 'SEND_EMAIL', 'NOTE')")
    op.execute((
        "ALTER TABLE admyral.action_node ALTER COLUMN action_type TYPE admyral.actiontype USING admyral.action_node.action_type::text::admyral.actiontype"
    ))
    op.execute("DROP TYPE admyral.actiontype_old")
    # ### end Alembic commands ###
