"""add is_error to workflow_run_action_state

Revision ID: b43779be43da
Revises: 8bc2d1453ebe
Create Date: 2024-05-01 13:10:51.223001

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b43779be43da'
down_revision = '8bc2d1453ebe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_run_action_state', sa.Column('is_error', sa.Boolean(), nullable=False, server_default=str(False)), schema='admyral')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_run_action_state', 'is_error', schema='admyral')
    # ### end Alembic commands ###
