"""add slack to integration type

Revision ID: d4cd7f559526
Revises: 37d9571b67ee
Create Date: 2024-05-25 15:19:04.566227

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4cd7f559526'
down_revision = '37d9571b67ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE admyral.integrationtype ADD VALUE 'SLACK';")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE admyral.integrationtype RENAME TO integrationtype_old")
    op.execute("CREATE TYPE admyral.integrationtype AS ENUM('VIRUS_TOTAL', 'ALIENVAULT_OTX', 'YARAIFY', 'THREATPOST', 'PHISH_REPORT')")
    op.execute((
        "ALTER TABLE admyral.credential ALTER COLUMN credential_type TYPE admyral.integrationtype USING admyral.credential.credential_type::text::admyral.integrationtype"
    ))
    op.execute((
        "ALTER TABLE admyral.workflow_template_metadata ALTER COLUMN icon TYPE admyral.integrationtype USING admyral.workflow_template_metadata.icon::text::admyral.integrationtype"
    ))    
    op.execute("DROP TYPE admyral.integrationtype_old")
    # ### end Alembic commands ###
