"""add error column to workflow run table

Revision ID: f3d9ded07cd8
Revises: 81da09e8f6fc
Create Date: 2024-06-04 22:31:43.067958

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3d9ded07cd8'
down_revision = '81da09e8f6fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_run', sa.Column('error', sa.TEXT(), nullable=True), schema='admyral')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_run', 'error', schema='admyral')
    # ### end Alembic commands ###
