"""add ai action to actiontype enum

Revision ID: f41c0e515eef
Revises: d6c366fcdd68
Create Date: 2024-04-22 14:07:01.578598

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f41c0e515eef'
down_revision = 'd6c366fcdd68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE admyral.actiontype ADD VALUE 'AI_ACTION';")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE admyral.actiontype RENAME TO actiontype_old")
    op.execute("CREATE TYPE admyral.actiontype AS ENUM('HTTP_REQUEST', 'WEBHOOK', 'IF_CONDITION')")
    op.execute((
        "ALTER TABLE admyral.action_node ALTER COLUMN action_type TYPE admyral.actiontype USING admyral.action_node.action_type::text::admyral.actiontype"
    ))
    op.execute("DROP TYPE admyral.actiontype_old")
    # ### end Alembic commands ###
