name: Publish PyPI Package
on:
  workflow_call:
jobs:
  publish_to_pypi:
    name: Publish Python package to PyPI
    runs-on: ubuntu-latest
    # Set permissions for trusted publishing.
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4.1.1
      # - name: Get the version from the github tag ref
      #   id: get_version
      #   run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install Poetry
        uses: snok/install-poetry@v1.4.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      # - name: Update version (kept at 0.0.0) in pyproject.toml and build
      #   run: |
      #     poetry version ${{ github.ref_name }}
      #     poetry build
      - name: Build package
        run: poetry build
      - name: Mint token
        id: mint
        uses: tschm/token-mint-action@v1.0.2
      - name: Publish the package with poetry
        run: |
          poetry publish -u __token__ -p '${{ steps.mint.outputs.api-token }}'
