# TODO: switch to a tag-based approach later
name: Publish PyPI Package
on:
  workflow_call:
jobs:
  publish_to_pypi:
    name: Publish Python package to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Poetry
        uses: snok/install-poetry@v1.4.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Build package
        run: poetry build

      - name: Build package
        run: poetry build

      - name: Extract version from pyproject.toml
        id: get_version
        run: |
          version=$(grep '^version = ' pyproject.toml | sed -E 's/version = "(.*)"/\1/')
          echo "Package version: $version"
          echo "::set-output name=VERSION::$version"

      - name: Get the latest published version from PyPI
        id: get_pypi_version
        run: |
          package_name=$(grep '^name = ' pyproject.toml | sed -E 's/name = "(.*)"/\1/')
          latest_version=$(curl -s https://pypi.org/pypi/$package_name/json | jq -r '.info.version')
          echo "Latest version on PyPI: $latest_version"
          echo "::set-output name=LATEST_VERSION::$latest_version"

      - name: Publish the package with poetry if the version has changed
        if: steps.get_version.outputs.VERSION != steps.get_pypi_version.outputs.LATEST_VERSION
        run: poetry publish -u __token__ -p '${{ secrets.PYPI_API_TOKEN }}'
