name: Publish PyPI Package
on:
  workflow_call:
jobs:
  publish_to_pypi:
    name: Publish Python package to PyPI
    runs-on: ubuntu-latest
    # Set permissions for trusted publishing.
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install Poetry
        uses: snok/install-poetry@v1.4.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Build package
        run: poetry build
      - name: Build package
        run: poetry build
      - name: Publish the package with poetry
        run: |
          poetry publish -u __token__ -p '${{ secrets.PYPI_API_TOKEN }}'
