name: Publish Docker Images
on:
  workflow_call:
    inputs:
      os:
        description: OS
        required: false
        default: ubuntu-latest
        type: string
      git-ref:
        description: Git branch or ref
        required: false
        default: ""
        type: string
jobs:
  publish-to-docker-hub:
    name: Publish Docker Images
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Extract version from pyproject.toml
        id: get_version
        run: |
          version=$(grep '^version = ' pyproject.toml | sed -E 's/version = "(.*)"/\1/')
          echo "Package version: $version"
          echo "::set-output name=VERSION::$version"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: cd docker && ./release_images.sh ${{ steps.get_version.outputs.VERSION }}
