name: Publish Docker Images
on:
    workflow_call:
        inputs:
            os:
                description: OS
                required: false
                default: ubuntu-latest
            git-ref:
                description: Git branch or ref
                required: false
                default: ""
jobs:
    publish-to-docker-hub:
        name: Publish Docker Images
        runs-on: ${{ inputs.os }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  repository: ${{ github.repository }}
                  ref: ${{ github.event.pull_request.head.sha }}
            - name: Login to docker hub
              uses: actions-hub/docker/login@master
              env:
              		DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            - name: Use Docker CLI
              uses: actions-hub/docker/cli@master
            - name: Build and push Docker images
							run: cd docker && ./release_images.sh
